#!/usr/bin/env sh

# Unfortunately it's not easy to directly use Polybar colour values in this
# script so I have to redefine some of my colours here. See the link below for
# more details:
# https://github.com/polybar/polybar/wiki/Formatting#format-tags-inside-polybar-config
green=#55aa55

configs_path="/etc/wireguard"
connected_interface=$(networkctl | rg "\d+ .* wireguard routable" -o | cut -d" " -f2)

connect() {
    all_configs=$(fd ".conf" /etc/wireguard | xargs basename -a -s .conf)
    count_of_configs=$(echo $all_configs | wc -l)
    if [ "$count_of_configs" -eq "1" ]; then
      selected_config=$all_configs
    else
      selected_config=$(echo $all_configs | rofi -dmenu -theme $HOME/.config/rofi/launcher/style-5.rasi)
    fi
    [[ $selected_config ]] && sudo wg-quick up "$configs_path"/"$selected_config".conf
}

disconnect() {
    # Normally we should have a single connected interface but technically
    # there's nothing stopping us from having multiple active intgerfaces so
    # let's do this in a loop:
    for connected_config in $(networkctl | grep -P "\d+ .* wireguard routable" -o | cut -d" " -f2)
    do
        sudo wg-quick down $configs_path/"$connected_config".conf
    done
}

toggle() {
    if [[ $connected_interface ]]
    then
        disconnect
    else
        connect
    fi
}

print() {
    if [[ $connected_interface ]]
    then
        echo %{u"$green"}%{+u}%{T4}%{F"$green"}%{T-}%{F-} "$connected_interface"
    else
        echo %{T4}%{T-}
    fi
}

case "$1" in
    --connect)
        connect
        ;;
    --disconnect)
        disconnect
        ;;
    --toggle)
        toggle
        ;;
    *)
        print
        ;;
esac
